language: node_js
node_js:
  - 11
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: www
  on:
    branch: master