/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MonthCalendar {
    'endDate': Date;
    'startDate': Date;
    'startOnSundays': Boolean;
  }
  interface MonthCalendarAttributes extends StencilHTMLAttributes {
    'endDate'?: Date;
    'startDate'?: Date;
    'startOnSundays'?: Boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MonthCalendar': Components.MonthCalendar;
  }

  interface StencilIntrinsicElements {
    'month-calendar': Components.MonthCalendarAttributes;
  }


  interface HTMLMonthCalendarElement extends Components.MonthCalendar, HTMLStencilElement {}
  var HTMLMonthCalendarElement: {
    prototype: HTMLMonthCalendarElement;
    new (): HTMLMonthCalendarElement;
  };

  interface HTMLElementTagNameMap {
    'month-calendar': HTMLMonthCalendarElement
  }

  interface ElementTagNameMap {
    'month-calendar': HTMLMonthCalendarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
